# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'monitor.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QFrame,
    QGroupBox, QLabel, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSlider,
    QSpinBox, QStackedWidget, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1404, 802)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionClose_app = QAction(MainWindow)
        self.actionClose_app.setObjectName(u"actionClose_app")
        self.actionGPS_map = QAction(MainWindow)
        self.actionGPS_map.setObjectName(u"actionGPS_map")
        self.actionECU_status_graph = QAction(MainWindow)
        self.actionECU_status_graph.setObjectName(u"actionECU_status_graph")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Visualization = QGroupBox(self.centralwidget)
        self.Visualization.setObjectName(u"Visualization")
        self.Visualization.setGeometry(QRect(10, 20, 651, 511))
        self.Visualization_YourDevice = QGroupBox(self.Visualization)
        self.Visualization_YourDevice.setObjectName(u"Visualization_YourDevice")
        self.Visualization_YourDevice.setGeometry(QRect(10, 40, 301, 311))
        self.Visualization_Back_Distance_Sensor_Right = QLabel(self.Visualization_YourDevice)
        self.Visualization_Back_Distance_Sensor_Right.setObjectName(u"Visualization_Back_Distance_Sensor_Right")
        self.Visualization_Back_Distance_Sensor_Right.setGeometry(QRect(190, 230, 66, 31))
        self.Visualization_Back_Distance_Sensor_Right.setAlignment(Qt.AlignCenter)
        self.Visualization_Back_Distance_Sensor_Left = QLabel(self.Visualization_YourDevice)
        self.Visualization_Back_Distance_Sensor_Left.setObjectName(u"Visualization_Back_Distance_Sensor_Left")
        self.Visualization_Back_Distance_Sensor_Left.setGeometry(QRect(50, 230, 66, 31))
        self.Visualization_Back_Distance_Sensor_Left.setAlignment(Qt.AlignCenter)
        self.Visualization_Back_Distance_Sensor_Center = QLabel(self.Visualization_YourDevice)
        self.Visualization_Back_Distance_Sensor_Center.setObjectName(u"Visualization_Back_Distance_Sensor_Center")
        self.Visualization_Back_Distance_Sensor_Center.setGeometry(QRect(120, 230, 66, 31))
        self.Visualization_Back_Distance_Sensor_Center.setAlignment(Qt.AlignCenter)
        self.Visualization_YourDeviceBox = QLabel(self.Visualization_YourDevice)
        self.Visualization_YourDeviceBox.setObjectName(u"Visualization_YourDeviceBox")
        self.Visualization_YourDeviceBox.setGeometry(QRect(80, 80, 140, 140))
        font = QFont()
        font.setBold(True)
        self.Visualization_YourDeviceBox.setFont(font)
        self.Visualization_YourDeviceBox.setCursor(QCursor(Qt.BlankCursor))
        self.Visualization_YourDeviceBox.setContextMenuPolicy(Qt.NoContextMenu)
        self.Visualization_YourDeviceBox.setFrameShape(QFrame.Box)
        self.Visualization_YourDeviceBox.setLineWidth(3)
        self.Visualization_YourDeviceBox.setAlignment(Qt.AlignCenter)
        self.Visualization_YourDeviceBox.setWordWrap(True)
        self.Visualization_Front_Distance_Sensor_Left = QLabel(self.Visualization_YourDevice)
        self.Visualization_Front_Distance_Sensor_Left.setObjectName(u"Visualization_Front_Distance_Sensor_Left")
        self.Visualization_Front_Distance_Sensor_Left.setGeometry(QRect(50, 40, 66, 31))
        self.Visualization_Front_Distance_Sensor_Left.setAlignment(Qt.AlignCenter)
        self.Visualization_Front_Distance_Sensor_Right = QLabel(self.Visualization_YourDevice)
        self.Visualization_Front_Distance_Sensor_Right.setObjectName(u"Visualization_Front_Distance_Sensor_Right")
        self.Visualization_Front_Distance_Sensor_Right.setGeometry(QRect(190, 40, 66, 31))
        self.Visualization_Front_Distance_Sensor_Right.setAlignment(Qt.AlignCenter)
        self.Visualization_Front_Distance_Sensor_Center = QLabel(self.Visualization_YourDevice)
        self.Visualization_Front_Distance_Sensor_Center.setObjectName(u"Visualization_Front_Distance_Sensor_Center")
        self.Visualization_Front_Distance_Sensor_Center.setGeometry(QRect(120, 40, 66, 31))
        self.Visualization_Front_Distance_Sensor_Center.setAlignment(Qt.AlignCenter)
        self.Visualization_EngineSelect_FrontRight = QPushButton(self.Visualization_YourDevice)
        self.Visualization_EngineSelect_FrontRight.setObjectName(u"Visualization_EngineSelect_FrontRight")
        self.Visualization_EngineSelect_FrontRight.setGeometry(QRect(230, 80, 51, 41))
        self.Visualization_EngineSelect_BackRight = QPushButton(self.Visualization_YourDevice)
        self.Visualization_EngineSelect_BackRight.setObjectName(u"Visualization_EngineSelect_BackRight")
        self.Visualization_EngineSelect_BackRight.setGeometry(QRect(230, 180, 51, 41))
        self.Visualization_EngineSelect_BackLeft = QPushButton(self.Visualization_YourDevice)
        self.Visualization_EngineSelect_BackLeft.setObjectName(u"Visualization_EngineSelect_BackLeft")
        self.Visualization_EngineSelect_BackLeft.setGeometry(QRect(20, 180, 51, 41))
        self.Visualization_EngineSelect_FrontLeft = QPushButton(self.Visualization_YourDevice)
        self.Visualization_EngineSelect_FrontLeft.setObjectName(u"Visualization_EngineSelect_FrontLeft")
        self.Visualization_EngineSelect_FrontLeft.setGeometry(QRect(20, 80, 51, 41))
        self.Visualization_EngineSpeedSpinBox = QSpinBox(self.Visualization_YourDevice)
        self.Visualization_EngineSpeedSpinBox.setObjectName(u"Visualization_EngineSpeedSpinBox")
        self.Visualization_EngineSpeedSpinBox.setGeometry(QRect(100, 270, 81, 27))
        self.Visualization_EngineSpeedSpinBox.setMinimum(-100)
        self.Visualization_EngineSpeedSpinBox.setMaximum(100)
        self.Visualization_EngineSpeedSpinBox.setStepType(QAbstractSpinBox.DefaultStepType)
        self.Visualization_EngineSpeed_Set = QPushButton(self.Visualization_YourDevice)
        self.Visualization_EngineSpeed_Set.setObjectName(u"Visualization_EngineSpeed_Set")
        self.Visualization_EngineSpeed_Set.setGeometry(QRect(190, 270, 88, 31))
        self.Control = QGroupBox(self.Visualization)
        self.Control.setObjectName(u"Control")
        self.Control.setGeometry(QRect(330, 40, 301, 311))
        self.Control_Front_Motor_Control_Slider_Left = QSlider(self.Control)
        self.Control_Front_Motor_Control_Slider_Left.setObjectName(u"Control_Front_Motor_Control_Slider_Left")
        self.Control_Front_Motor_Control_Slider_Left.setGeometry(QRect(70, 30, 16, 221))
        self.Control_Front_Motor_Control_Slider_Left.setMinimum(-100)
        self.Control_Front_Motor_Control_Slider_Left.setMaximum(100)
        self.Control_Front_Motor_Control_Slider_Left.setOrientation(Qt.Vertical)
        self.Control_Front_Motor_Control_Slider_Right = QSlider(self.Control)
        self.Control_Front_Motor_Control_Slider_Right.setObjectName(u"Control_Front_Motor_Control_Slider_Right")
        self.Control_Front_Motor_Control_Slider_Right.setGeometry(QRect(100, 30, 16, 221))
        self.Control_Front_Motor_Control_Slider_Right.setMinimum(-100)
        self.Control_Front_Motor_Control_Slider_Right.setMaximum(100)
        self.Control_Front_Motor_Control_Slider_Right.setOrientation(Qt.Vertical)
        self.Control_Back_Motor_Control_Slider_Left = QSlider(self.Control)
        self.Control_Back_Motor_Control_Slider_Left.setObjectName(u"Control_Back_Motor_Control_Slider_Left")
        self.Control_Back_Motor_Control_Slider_Left.setGeometry(QRect(130, 30, 16, 221))
        self.Control_Back_Motor_Control_Slider_Left.setMinimum(-100)
        self.Control_Back_Motor_Control_Slider_Left.setMaximum(100)
        self.Control_Back_Motor_Control_Slider_Left.setOrientation(Qt.Vertical)
        self.Control_Back_Motor_Control_Slider_Right = QSlider(self.Control)
        self.Control_Back_Motor_Control_Slider_Right.setObjectName(u"Control_Back_Motor_Control_Slider_Right")
        self.Control_Back_Motor_Control_Slider_Right.setGeometry(QRect(160, 30, 16, 221))
        self.Control_Back_Motor_Control_Slider_Right.setMinimum(-100)
        self.Control_Back_Motor_Control_Slider_Right.setMaximum(100)
        self.Control_Back_Motor_Control_Slider_Right.setOrientation(Qt.Vertical)
        self.Control_Front_LeftRight = QLabel(self.Control)
        self.Control_Front_LeftRight.setObjectName(u"Control_Front_LeftRight")
        self.Control_Front_LeftRight.setGeometry(QRect(70, 250, 41, 18))
        self.Control_Front_LeftRight.setAlignment(Qt.AlignCenter)
        self.Control_Back_LeftRight = QLabel(self.Control)
        self.Control_Back_LeftRight.setObjectName(u"Control_Back_LeftRight")
        self.Control_Back_LeftRight.setGeometry(QRect(130, 250, 41, 20))
        self.Control_Back_LeftRight.setAlignment(Qt.AlignCenter)
        self.Control_Back = QLabel(self.Control)
        self.Control_Back.setObjectName(u"Control_Back")
        self.Control_Back.setGeometry(QRect(120, 270, 61, 18))
        self.Control_Back.setAlignment(Qt.AlignCenter)
        self.Control_Front = QLabel(self.Control)
        self.Control_Front.setObjectName(u"Control_Front")
        self.Control_Front.setGeometry(QRect(70, 270, 41, 18))
        self.Control_Front.setAlignment(Qt.AlignCenter)
        self.Control_StartStop = QPushButton(self.Control)
        self.Control_StartStop.setObjectName(u"Control_StartStop")
        self.Control_StartStop.setGeometry(QRect(200, 30, 88, 31))
        self.Control_MoveForward = QPushButton(self.Control)
        self.Control_MoveForward.setObjectName(u"Control_MoveForward")
        self.Control_MoveForward.setGeometry(QRect(200, 70, 88, 31))
        self.Control_MoveBackward = QPushButton(self.Control)
        self.Control_MoveBackward.setObjectName(u"Control_MoveBackward")
        self.Control_MoveBackward.setGeometry(QRect(200, 110, 88, 31))
        self.Control_PercentPositive100 = QLabel(self.Control)
        self.Control_PercentPositive100.setObjectName(u"Control_PercentPositive100")
        self.Control_PercentPositive100.setGeometry(QRect(10, 30, 66, 18))
        self.Control_PercentNegative100 = QLabel(self.Control)
        self.Control_PercentNegative100.setObjectName(u"Control_PercentNegative100")
        self.Control_PercentNegative100.setGeometry(QRect(10, 230, 66, 18))
        self.Control_PercentZero = QLabel(self.Control)
        self.Control_PercentZero.setObjectName(u"Control_PercentZero")
        self.Control_PercentZero.setGeometry(QRect(10, 130, 66, 18))
        self.Control_EngineSpeedSpinBox = QSpinBox(self.Control)
        self.Control_EngineSpeedSpinBox.setObjectName(u"Control_EngineSpeedSpinBox")
        self.Control_EngineSpeedSpinBox.setGeometry(QRect(200, 220, 81, 27))
        self.Control_EngineSpeedSpinBox.setMinimum(-100)
        self.Control_EngineSpeedSpinBox.setMaximum(100)
        self.Control_EngineSpeedSpinBox.setStepType(QAbstractSpinBox.DefaultStepType)
        self.Control_EngineSelect_Front = QComboBox(self.Control)
        self.Control_EngineSelect_Front.addItem("")
        self.Control_EngineSelect_Front.addItem("")
        self.Control_EngineSelect_Front.addItem("")
        self.Control_EngineSelect_Front.addItem("")
        self.Control_EngineSelect_Front.setObjectName(u"Control_EngineSelect_Front")
        self.Control_EngineSelect_Front.setGeometry(QRect(200, 190, 86, 26))
        self.Control_EngineSelect_Front.setEditable(False)
        self.Control_EngineSelect_Front_2 = QComboBox(self.Control)
        self.Control_EngineSelect_Front_2.addItem("")
        self.Control_EngineSelect_Front_2.addItem("")
        self.Control_EngineSelect_Front_2.addItem("")
        self.Control_EngineSelect_Front_2.addItem("")
        self.Control_EngineSelect_Front_2.setObjectName(u"Control_EngineSelect_Front_2")
        self.Control_EngineSelect_Front_2.setGeometry(QRect(200, 160, 86, 26))
        self.Control_EngineSelect_Front_2.setEditable(False)
        self.Control_EngineSpeed = QPushButton(self.Control)
        self.Control_EngineSpeed.setObjectName(u"Control_EngineSpeed")
        self.Control_EngineSpeed.setGeometry(QRect(200, 250, 88, 31))
        self.Visualization_MonitorApp_Status = QLabel(self.Visualization)
        self.Visualization_MonitorApp_Status.setObjectName(u"Visualization_MonitorApp_Status")
        self.Visualization_MonitorApp_Status.setGeometry(QRect(10, 360, 621, 91))
        self.Visualization_MonitorApp_Status.setFrameShape(QFrame.NoFrame)
        self.Visualization_MonitorApp_Status.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.Visualization_MonitorApp_StatusControl_Box = QGroupBox(self.Visualization)
        self.Visualization_MonitorApp_StatusControl_Box.setObjectName(u"Visualization_MonitorApp_StatusControl_Box")
        self.Visualization_MonitorApp_StatusControl_Box.setGeometry(QRect(460, 460, 191, 51))
        self.Visualization_MonitorApp_Status_Copy2Clipboard = QPushButton(self.Visualization_MonitorApp_StatusControl_Box)
        self.Visualization_MonitorApp_Status_Copy2Clipboard.setObjectName(u"Visualization_MonitorApp_Status_Copy2Clipboard")
        self.Visualization_MonitorApp_Status_Copy2Clipboard.setGeometry(QRect(10, 10, 88, 31))
        self.Visualization_MonitorApp_Status_Clear = QPushButton(self.Visualization_MonitorApp_StatusControl_Box)
        self.Visualization_MonitorApp_Status_Clear.setObjectName(u"Visualization_MonitorApp_Status_Clear")
        self.Visualization_MonitorApp_Status_Clear.setGeometry(QRect(100, 10, 88, 31))
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(680, 40, 641, 491))
        self.stackedWidget.setFrameShape(QFrame.Box)
        self.Graph_Stack = QWidget()
        self.Graph_Stack.setObjectName(u"Graph_Stack")
        self.Graph_ECUStatus = QWidget(self.Graph_Stack)
        self.Graph_ECUStatus.setObjectName(u"Graph_ECUStatus")
        self.Graph_ECUStatus.setGeometry(QRect(10, 30, 611, 431))
        self.stackedWidget.addWidget(self.Graph_Stack)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.Graph_ECUStatus_GPSMap = QWebEngineView(self.page_2)
        self.Graph_ECUStatus_GPSMap.setObjectName(u"Graph_ECUStatus_GPSMap")
        self.Graph_ECUStatus_GPSMap.setGeometry(QRect(10, 10, 621, 471))
        self.Graph_ECUStatus_GPSMap.setUrl(QUrl(u"about:blank"))
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1404, 23))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionClose_app)
        self.menuView.addAction(self.actionGPS_map)
        self.menuView.addAction(self.actionECU_status_graph)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Open config", None))
        self.actionClose_app.setText(QCoreApplication.translate("MainWindow", u"Close app", None))
        self.actionGPS_map.setText(QCoreApplication.translate("MainWindow", u"GPS map", None))
        self.actionECU_status_graph.setText(QCoreApplication.translate("MainWindow", u"ECU status graph ", None))
        self.Visualization.setTitle(QCoreApplication.translate("MainWindow", u"Visualization", None))
        self.Visualization_YourDevice.setTitle(QCoreApplication.translate("MainWindow", u"YourDevice", None))
        self.Visualization_Back_Distance_Sensor_Right.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_Back_Distance_Sensor_Left.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_Back_Distance_Sensor_Center.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_YourDeviceBox.setText(QCoreApplication.translate("MainWindow", u"Your Device", None))
        self.Visualization_Front_Distance_Sensor_Left.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_Front_Distance_Sensor_Right.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_Front_Distance_Sensor_Center.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_EngineSelect_FrontRight.setText(QCoreApplication.translate("MainWindow", u"Eng", None))
        self.Visualization_EngineSelect_BackRight.setText(QCoreApplication.translate("MainWindow", u"Eng", None))
        self.Visualization_EngineSelect_BackLeft.setText(QCoreApplication.translate("MainWindow", u"Eng", None))
        self.Visualization_EngineSelect_FrontLeft.setText(QCoreApplication.translate("MainWindow", u"Eng", None))
        self.Visualization_EngineSpeed_Set.setText(QCoreApplication.translate("MainWindow", u"Set speed", None))
        self.Control.setTitle(QCoreApplication.translate("MainWindow", u"Control", None))
        self.Control_Front_LeftRight.setText(QCoreApplication.translate("MainWindow", u"L       R", None))
        self.Control_Back_LeftRight.setText(QCoreApplication.translate("MainWindow", u"L       R", None))
        self.Control_Back.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.Control_Front.setText(QCoreApplication.translate("MainWindow", u"Front", None))
        self.Control_StartStop.setText(QCoreApplication.translate("MainWindow", u"Start/Stop", None))
        self.Control_MoveForward.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
        self.Control_MoveBackward.setText(QCoreApplication.translate("MainWindow", u"Backward", None))
        self.Control_PercentPositive100.setText(QCoreApplication.translate("MainWindow", u"+100%", None))
        self.Control_PercentNegative100.setText(QCoreApplication.translate("MainWindow", u"-100%", None))
        self.Control_PercentZero.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.Control_EngineSelect_Front.setItemText(0, QCoreApplication.translate("MainWindow", u"Back_LR", None))
        self.Control_EngineSelect_Front.setItemText(1, QCoreApplication.translate("MainWindow", u"Back_L", None))
        self.Control_EngineSelect_Front.setItemText(2, QCoreApplication.translate("MainWindow", u"Back_R", None))
        self.Control_EngineSelect_Front.setItemText(3, QCoreApplication.translate("MainWindow", u"None", None))

        self.Control_EngineSelect_Front.setCurrentText(QCoreApplication.translate("MainWindow", u"Back_LR", None))
        self.Control_EngineSelect_Front_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Front_LR", None))
        self.Control_EngineSelect_Front_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Front_L", None))
        self.Control_EngineSelect_Front_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Front_R", None))
        self.Control_EngineSelect_Front_2.setItemText(3, QCoreApplication.translate("MainWindow", u"None", None))

        self.Control_EngineSelect_Front_2.setCurrentText(QCoreApplication.translate("MainWindow", u"Front_LR", None))
        self.Control_EngineSpeed.setText(QCoreApplication.translate("MainWindow", u"Set speed", None))
        self.Visualization_MonitorApp_Status.setText(QCoreApplication.translate("MainWindow", u"<Status>", None))
        self.Visualization_MonitorApp_StatusControl_Box.setTitle("")
        self.Visualization_MonitorApp_Status_Copy2Clipboard.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.Visualization_MonitorApp_Status_Clear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

