# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'monitor.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1415, 554)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionClose_app = QAction(MainWindow)
        self.actionClose_app.setObjectName(u"actionClose_app")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Visualization = QGroupBox(self.centralwidget)
        self.Visualization.setObjectName(u"Visualization")
        self.Visualization.setGeometry(QRect(10, 20, 651, 481))
        self.Visualization_YourDevice = QGroupBox(self.Visualization)
        self.Visualization_YourDevice.setObjectName(u"Visualization_YourDevice")
        self.Visualization_YourDevice.setGeometry(QRect(10, 40, 301, 311))
        self.Visualization_Back_Distance_Sensor_Right = QLabel(self.Visualization_YourDevice)
        self.Visualization_Back_Distance_Sensor_Right.setObjectName(u"Visualization_Back_Distance_Sensor_Right")
        self.Visualization_Back_Distance_Sensor_Right.setGeometry(QRect(200, 240, 66, 31))
        self.Visualization_Back_Distance_Sensor_Right.setAlignment(Qt.AlignCenter)
        self.Visualization_Back_Distance_Sensor_Left = QLabel(self.Visualization_YourDevice)
        self.Visualization_Back_Distance_Sensor_Left.setObjectName(u"Visualization_Back_Distance_Sensor_Left")
        self.Visualization_Back_Distance_Sensor_Left.setGeometry(QRect(30, 240, 66, 31))
        self.Visualization_Back_Distance_Sensor_Left.setAlignment(Qt.AlignCenter)
        self.Visualization_Back_Distance_Sensor_Center = QLabel(self.Visualization_YourDevice)
        self.Visualization_Back_Distance_Sensor_Center.setObjectName(u"Visualization_Back_Distance_Sensor_Center")
        self.Visualization_Back_Distance_Sensor_Center.setGeometry(QRect(110, 270, 66, 31))
        self.Visualization_Back_Distance_Sensor_Center.setAlignment(Qt.AlignCenter)
        self.Visualization_YourDeviceBox = QLabel(self.Visualization_YourDevice)
        self.Visualization_YourDeviceBox.setObjectName(u"Visualization_YourDeviceBox")
        self.Visualization_YourDeviceBox.setGeometry(QRect(70, 100, 140, 140))
        font = QFont()
        font.setBold(True)
        self.Visualization_YourDeviceBox.setFont(font)
        self.Visualization_YourDeviceBox.setCursor(QCursor(Qt.BlankCursor))
        self.Visualization_YourDeviceBox.setContextMenuPolicy(Qt.NoContextMenu)
        self.Visualization_YourDeviceBox.setFrameShape(QFrame.Box)
        self.Visualization_YourDeviceBox.setLineWidth(3)
        self.Visualization_YourDeviceBox.setAlignment(Qt.AlignCenter)
        self.Visualization_YourDeviceBox.setWordWrap(True)
        self.Visualization_Front_Distance_Sensor_Left = QLabel(self.Visualization_YourDevice)
        self.Visualization_Front_Distance_Sensor_Left.setObjectName(u"Visualization_Front_Distance_Sensor_Left")
        self.Visualization_Front_Distance_Sensor_Left.setGeometry(QRect(30, 70, 66, 31))
        self.Visualization_Front_Distance_Sensor_Left.setAlignment(Qt.AlignCenter)
        self.Visualization_Front_Distance_Sensor_Right = QLabel(self.Visualization_YourDevice)
        self.Visualization_Front_Distance_Sensor_Right.setObjectName(u"Visualization_Front_Distance_Sensor_Right")
        self.Visualization_Front_Distance_Sensor_Right.setGeometry(QRect(200, 70, 66, 31))
        self.Visualization_Front_Distance_Sensor_Right.setAlignment(Qt.AlignCenter)
        self.Visualization_Front_Distance_Sensor_Center = QLabel(self.Visualization_YourDevice)
        self.Visualization_Front_Distance_Sensor_Center.setObjectName(u"Visualization_Front_Distance_Sensor_Center")
        self.Visualization_Front_Distance_Sensor_Center.setGeometry(QRect(110, 40, 66, 31))
        self.Visualization_Front_Distance_Sensor_Center.setAlignment(Qt.AlignCenter)
        self.Control = QGroupBox(self.Visualization)
        self.Control.setObjectName(u"Control")
        self.Control.setGeometry(QRect(330, 40, 301, 311))
        self.Control_Front_Motor_Control_Slider_Left = QSlider(self.Control)
        self.Control_Front_Motor_Control_Slider_Left.setObjectName(u"Control_Front_Motor_Control_Slider_Left")
        self.Control_Front_Motor_Control_Slider_Left.setGeometry(QRect(70, 30, 16, 221))
        self.Control_Front_Motor_Control_Slider_Left.setMinimum(-100)
        self.Control_Front_Motor_Control_Slider_Left.setMaximum(100)
        self.Control_Front_Motor_Control_Slider_Left.setOrientation(Qt.Vertical)
        self.Control_Front_Motor_Control_Slider_Right = QSlider(self.Control)
        self.Control_Front_Motor_Control_Slider_Right.setObjectName(u"Control_Front_Motor_Control_Slider_Right")
        self.Control_Front_Motor_Control_Slider_Right.setGeometry(QRect(100, 30, 16, 221))
        self.Control_Front_Motor_Control_Slider_Right.setMinimum(-100)
        self.Control_Front_Motor_Control_Slider_Right.setMaximum(100)
        self.Control_Front_Motor_Control_Slider_Right.setOrientation(Qt.Vertical)
        self.Control_Back_Motor_Control_Slider_Left = QSlider(self.Control)
        self.Control_Back_Motor_Control_Slider_Left.setObjectName(u"Control_Back_Motor_Control_Slider_Left")
        self.Control_Back_Motor_Control_Slider_Left.setGeometry(QRect(130, 30, 16, 221))
        self.Control_Back_Motor_Control_Slider_Left.setMinimum(-100)
        self.Control_Back_Motor_Control_Slider_Left.setMaximum(100)
        self.Control_Back_Motor_Control_Slider_Left.setOrientation(Qt.Vertical)
        self.Control_Back_Motor_Control_Slider_Right = QSlider(self.Control)
        self.Control_Back_Motor_Control_Slider_Right.setObjectName(u"Control_Back_Motor_Control_Slider_Right")
        self.Control_Back_Motor_Control_Slider_Right.setGeometry(QRect(160, 30, 16, 221))
        self.Control_Back_Motor_Control_Slider_Right.setMinimum(-100)
        self.Control_Back_Motor_Control_Slider_Right.setMaximum(100)
        self.Control_Back_Motor_Control_Slider_Right.setOrientation(Qt.Vertical)
        self.Control_Front_LeftRight = QLabel(self.Control)
        self.Control_Front_LeftRight.setObjectName(u"Control_Front_LeftRight")
        self.Control_Front_LeftRight.setGeometry(QRect(70, 250, 41, 18))
        self.Control_Front_LeftRight.setAlignment(Qt.AlignCenter)
        self.Control_Back_LeftRight = QLabel(self.Control)
        self.Control_Back_LeftRight.setObjectName(u"Control_Back_LeftRight")
        self.Control_Back_LeftRight.setGeometry(QRect(130, 250, 41, 20))
        self.Control_Back_LeftRight.setAlignment(Qt.AlignCenter)
        self.Control_Back = QLabel(self.Control)
        self.Control_Back.setObjectName(u"Control_Back")
        self.Control_Back.setGeometry(QRect(120, 270, 61, 18))
        self.Control_Back.setAlignment(Qt.AlignCenter)
        self.Control_Front = QLabel(self.Control)
        self.Control_Front.setObjectName(u"Control_Front")
        self.Control_Front.setGeometry(QRect(70, 270, 41, 18))
        self.Control_Front.setAlignment(Qt.AlignCenter)
        self.Control_StartStop = QPushButton(self.Control)
        self.Control_StartStop.setObjectName(u"Control_StartStop")
        self.Control_StartStop.setGeometry(QRect(200, 30, 88, 31))
        self.Control_MoveForward = QPushButton(self.Control)
        self.Control_MoveForward.setObjectName(u"Control_MoveForward")
        self.Control_MoveForward.setGeometry(QRect(200, 80, 88, 31))
        self.Control_MoveBackward = QPushButton(self.Control)
        self.Control_MoveBackward.setObjectName(u"Control_MoveBackward")
        self.Control_MoveBackward.setGeometry(QRect(200, 130, 88, 31))
        self.Control_PercentPositive100 = QLabel(self.Control)
        self.Control_PercentPositive100.setObjectName(u"Control_PercentPositive100")
        self.Control_PercentPositive100.setGeometry(QRect(10, 30, 66, 18))
        self.Control_PercentNegative100 = QLabel(self.Control)
        self.Control_PercentNegative100.setObjectName(u"Control_PercentNegative100")
        self.Control_PercentNegative100.setGeometry(QRect(10, 230, 66, 18))
        self.Control_PercentZero = QLabel(self.Control)
        self.Control_PercentZero.setObjectName(u"Control_PercentZero")
        self.Control_PercentZero.setGeometry(QRect(10, 130, 66, 18))
        self.label = QLabel(self.Visualization)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 360, 621, 101))
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.Graph = QWidget(self.centralwidget)
        self.Graph.setObjectName(u"Graph")
        self.Graph.setGeometry(QRect(670, 40, 721, 461))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1415, 23))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionClose_app)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Open config", None))
        self.actionClose_app.setText(QCoreApplication.translate("MainWindow", u"Close app", None))
        self.Visualization.setTitle(QCoreApplication.translate("MainWindow", u"Visualization", None))
        self.Visualization_YourDevice.setTitle(QCoreApplication.translate("MainWindow", u"YourDevice", None))
        self.Visualization_Back_Distance_Sensor_Right.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_Back_Distance_Sensor_Left.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_Back_Distance_Sensor_Center.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_YourDeviceBox.setText(QCoreApplication.translate("MainWindow", u"Your Device", None))
        self.Visualization_Front_Distance_Sensor_Left.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_Front_Distance_Sensor_Right.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Visualization_Front_Distance_Sensor_Center.setText(QCoreApplication.translate("MainWindow", u"0.00m", None))
        self.Control.setTitle(QCoreApplication.translate("MainWindow", u"Control", None))
        self.Control_Front_LeftRight.setText(QCoreApplication.translate("MainWindow", u"L       R", None))
        self.Control_Back_LeftRight.setText(QCoreApplication.translate("MainWindow", u"L       R", None))
        self.Control_Back.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.Control_Front.setText(QCoreApplication.translate("MainWindow", u"Front", None))
        self.Control_StartStop.setText(QCoreApplication.translate("MainWindow", u"Start/Stop", None))
        self.Control_MoveForward.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
        self.Control_MoveBackward.setText(QCoreApplication.translate("MainWindow", u"Backward", None))
        self.Control_PercentPositive100.setText(QCoreApplication.translate("MainWindow", u"+100%", None))
        self.Control_PercentNegative100.setText(QCoreApplication.translate("MainWindow", u"-100%", None))
        self.Control_PercentZero.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<Status>", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

